### ISSUE TITLE
private-address: 127.0.0.0/8 stops dnsbl from working / make config snippets configurable

### ISSUE THREAD

**Issue by Yannik** [roles-ansible/ansible_role_unbound#9]
Hi,

I have recently noticed alot of spam getting through to my emailserver, and now I know why:
DNSBL's like work in a way that, for example for spamhaus, you query `ip.zen.spamhaus.org` or `domain.zen.spamhaus.org` and get either `NODATA` as a response or `127.0.0.x` if the ip/domain is blocked. (x specifies the reason why it is blocked, see https://www.spamhaus.org/zen/)

Since your `private-addresses.conf` contains a `private-address: 127.0.0.0/8` line, all `127.0.0.x` (blocking) responses are replaced by unbound an empty response. In effect breaking the dnsbl functionality.

I'm not a 100% whether dns rebinding is really a security issue for servers or whether this can safely be removed as a whole, I will do some research on that.

Generally speaking, it would sure be nice to provide some additional configurability for the templates. It would be nice if you could add snippets of your own or overwrite the existing ones.

**Comment by Yannik** [comment]
I have done some research, and imo dns rebinding is not an issue for servers, because it only occurs when accessing random untrusted domains (generally in a browser), which a server does not do.

**Comment by Yannik** [comment]
Another alternative I found to completely removing the `private-addresses` would be to add a custom snippet with this content: 
```
server:
  private-domain: spamhaus.org
```

**Comment by DO1JLR** [comment]
Sory for the long silence. I have now made the snipets a little more configurable. Maybe this will help you.

If you are missing any other features, feel free to submit a pull request.
I usually react a bit faster to such requests. :innocent:
